### ISSUE TITLE
Issue when Running TabPy Script

### ISSUE THREAD

**Issue by nicolaijohnson** [jhegele/TabStein#7]
I got to the step of running the Einstein script, but ran into an issue. Here's the error message from the terminal: 
TypeError : list indices must be integers or slices, not str
I set my predicted score field as a number (decimal), so not sure why I'm getting an error regarding string. Any ideas on how I can solve this?

- Nicolai

**Comment by jhegele** [comment]
This is likely because the chunk size is set too high. I set the default to be 2,000 as that never gave me any issues during development but, per the [Einstein Discovery API Documentation](https://help.salesforce.com/articleView?id=bi_edd_limits.htm&type=5) the actual limit is 200 rows per request. I'm still unsure why it worked for me so many times during development but my team and I saw this exact error and reducing the chunk size to 200 or lower corrected it for us. Let me know what you find!

**Comment by nicolaijohnson** [comment]
This solved the issue! Was able to score all the records in my dataset. Thanks for the help. 

By the way, what you built is super powerful - both TabStein and Einstein Scenarios. I work for a Salesforce SI that specializes in Einstein implementations. We just became Tableau partners, I've already used Einstein Scenarios on one project and countless pre-sales engagements. Customer is now interested to auto-score records weekly, TabStein will help with that!

**Comment by jhegele** [comment]
Thanks @nicolaijohnson! Really glad that you've found these useful! I'm going to close this issue but let me know if anything else pops up.
